### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by bjkeller** [Bioprotocols/PAML-specification#4]
As a user of a class having names that look like something that they are not is confusing:
- `hasName` reads like a predicate. Use `name` instead.
-  `activity` looks like the cardinality is one, for any other cardinality use `activities`

**Comment by jakebeal** [comment]
This is fixed in the python library as of this morning: https://github.com/SD2E/paml/commit/10f7f24a9d2c0c7326e1e9545bb02900c26e7b56

Note that there will continue to be a split between what the user sees (which should be pretty like you're suggesting) and the actual predicates under the covers, which are always singular and will often have uglier names.

If you see any that I missed, let me know.
